# =============================================================================
# Konfigurasi Utama
# =============================================================================
lang: id
timezone: Asia/Makassar

# =============================================================================
# Informasi Situs & Author (Sidebar Kiri)
# =============================================================================
title: Rezky Robbyyanto Akbari
tagline: Menjembatani Teknologi dan Strategi Bisnis Melalui Sistem Informasi.
description: Robby Work

# URL: Sudah benar sesuai nama repositori baru Anda
url: https://RezkyRobby23h.github.io
# 'baseurl' tidak diperlukan lagi karena nama repo sudah benar

author: Rezky Robbyyanto Akbari
avatar: /assets/img/avatar.jpg
email: reskybobby04@gmail.com

social:
  name: Rezky Robbyyanto Akbari
  email: reskybobby04@gmail.com
  links:
    - name: GitHub
      url: https://github.com/RezkyRobby23h

# =============================================================================
# Pengaturan Tampilan & Teknis
# =============================================================================
theme_mode: dual
github:
  username: RezkyRobby23h

# =============================================================================
# Pengaturan Build Jekyll (Jangan ubah bagian di bawah ini)
# =============================================================================
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]
paginate: 10
paginate_path: /page:num/
exclude:
  - .github/
  - .jekyll-cache/
  - .bundle/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - docs/